### ISSUE TITLE
ChatGPT安全问题

### ISSUE THREAD

**Issue by xy666aso** [mo-xiaoxi/GPTSecurity#10]
白皮书：
ChatGPT Security Risks: A Guide for Cyber Security Professionals 
https://www.cybertalk.org/wp-content/uploads/2023/03/ChatGPT_eBook_CP_CT_2023.pdf
ChatGPT的安全隐患
http://mtw.so/5TwZBb
博客：
安全测试中的 ChatGPT AI：机遇与挑战    https://www.cyfirma.com/outofband/chatgpt-ai-in-security-testing-opportunities-and-challenges/
ChatGPT 生成代码的安全漏洞    https://www.trendmicro.com/ja_jp/devops/23/e/chatgpt-security-vulnerabilities.html

**Comment by cloudymonstera** [comment]
请提供“ChatGPT的安全隐患”的可用链接；其余已收录。
