### ISSUE TITLE
security 

### ISSUE THREAD

**Issue by xy666aso** [mo-xiaoxi/GPTSecurity#13]
5 ChatGPT security risks in the enterprise
https://www.techtarget.com/searchsecurity/tip/ChatGPT-security-risks-in-the-enterprise
Security and Privacy with GPT
https://www.ambit.ai/resources/security-and-privacy-with-gpt
ChatGPT 的 10 个问题：它如何改变网络安全
https://socradar.io/10-questions-to-chatgpt-how-it-can-change-cybersecurity/
ChatGPT 和物联网安全：未来是什么？
https://www.iotforall.com/chatgpt-and-iot-security-what-is-the-future

**Comment by cloudymonstera** [comment]
请提供简单的推荐理由，并再次确认原创性
